# Site settings
author: Selamawit Lemma
title: Abey-C-Niya Blog
header-img: img/home-bg.png
email: oneiconforlife26@gmail.com
copyright_name: Selamawit Lemma
description: > # this means to ignore newlines until "baseurl:"
  Website Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Mimi-12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
